networks:
  docknode-apt-indexer:
    driver: bridge

volumes:
  db_indexer_data: {}
  db_hasura_data: {}
  caddy_data: {}
  caddy_config: {}

services:
  dbindexer:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db_indexer_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: aptindexer
    networks:
      - docknode-apt-indexer

  dbhasura:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db_hasura_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: hasura
    networks:
      - docknode-apt-indexer

  graphqlengine:
    image: hasura/graphql-engine:latest
    ports:
      - 8080:8080
    restart: always
    environment:
      # HASURA_GRAPHQL_DATABASE_URL: postgres://postgres_user:postgres_password@dbindexer:5432/aptindexer
      PG_DATABASE_URL: postgres://postgres_user:postgres_password@dbindexer:5432/aptindexer
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres_user:postgres_password@dbhasura:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey2
      HASURA_GRAPHQL_DEV_MODE: "false"
    networks:
      - docknode-apt-indexer

  nodeexporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - docknode-apt-indexer
